name: uber
description: Aplicacion de Prueba
authors:
  - DstudioVisual
# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  uuid: 2.0.4
  charts_flutter: any
  url_launcher: ^5.7.10
  flutter_custom_clippers: ^1.1.2
  flutter_ringtone_player: ^2.0.0
  firebase_core: ^0.7.0
  launch_review: ^1.0.1
  cool_alert: 1.0.3
  progress_dialog: ^1.2.0
  shared_preferences: ^0.5.12+4
  google_maps_flutter: ^1.0.6
  flutter_google_places: ^0.2.8
  geolocator: ^6.1.13
  native_updater: ^0.0.4
  location: ^3.1.0
  geoflutterfire: ^2.2.2
  geocoder: ^0.2.1
  geocoding: ^1.0.5
  flutter_polyline_points: ^0.2.4
  lottie: ^0.7.0+1
  firebase_messaging: ^8.0.0-dev.15
  modal_bottom_sheet: ^1.0.0+1
  flutter_rating_bar: ^3.2.0+1
  image_picker: ^0.6.5+2
  flutter_phone_direct_caller: ^1.0.1
  intl: ^0.16.0
  firebase_analytics: "^7.0.1"
  change: ^0.1.1
  audioplayers: ^0.14.2
  path_provider_windows: 0.0.4+3
  flutter_launcher_icons: "^0.8.1"
  change_app_package_name: ^0.1.2
  platform: ^2.2.1
  path_provider: 1.6.28
  firebase_auth: "^0.20.1"
  firebase_crashlytics: "^0.4.0"
  cloud_firestore: "^0.16.0"
  cloud_functions: "^0.9.0"
  firebase_storage: "^7.0.0"
  connectivity_plus: 0.8.1
  provider: 4.3.3
  slide_to_act: any




dev_dependencies:
  flutter_launcher_icons: "^0.8.1"
  change_app_package_name: ^0.1.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo.png"

  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  # adding or updating assets for this project.

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
  - assets/img/
  - assets/json/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
       - family: Pacifico
         fonts:
           - asset: assets/fonts/Pacifico/Pacifico.ttf
       - family: Roboto
         fonts:
           - asset: assets/fonts/Roboto/Roboto-Regular.ttf
       - family: RobotoMedium
         fonts:
           - asset: assets/fonts/Roboto/Roboto-Medium.ttf
       - family: NimbusSans
         fonts:
           - asset: assets/fonts/NimbusSans/NimbusSanL-Reg.otf
       - family: OneDay
         fonts:
            - asset: assets/fonts/OneDay/ONEDAY.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
